# -*- coding: utf-8 -*-
"""DATA_SCIENCE_PROJECT_FISH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XeRAiKvP90BLAcw3TxmP_LJDZgrZVktd
"""

import pandas as pd
import numpy as np

df = pd.read_csv('Fish.csv')

df.head()

df.shape

df.info()

df.describe()

features = df[['Height', 'Width']]
features.head()

labels = df[['Weight']]
labels.head()

from sklearn.model_selection import train_test_split
# it will return four variables, X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.15)

X_train.shape, X_test.shape

y_train.shape, y_test.shape

from sklearn import linear_model

model = linear_model.LinearRegression()

model.fit(X_train, y_train)

from sklearn.metrics import r2_score

predictions = model.predict(X_train)

r2 = r2_score(y_train, predictions)
print("R2 Score :", r2)

predictions = model.predict(X_test)

r2 = r2_score(y_test, predictions)
print("R2 Score :", r2)

from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt

x=df.iloc[:,[3,4]].values

x

hc = AgglomerativeClustering(n_clusters= 5 , affinity= 'euclidean', linkage='ward')

y_hc = hc.fit_predict(x)

# visualizing cluster

plt.figure(figsize =(6,6))

plt.scatter(x[y_hc==0,0],x[y_hc==0,1],s=100,c='red',label='Length1')

plt.scatter(x[y_hc==1,0],x[y_hc==1,1],s=100,c='blue',label='Length2')

plt.scatter(x[y_hc==2,0],x[y_hc==2,1],s=100,c='green',label='Length3')

plt.scatter(x[y_hc==0,0],x[y_hc==0,1],s=100,c='red',label='Length1')
plt.scatter(x[y_hc==1,0],x[y_hc==1,1],s=100,c='blue',label='Length2')
plt.scatter(x[y_hc==2,0],x[y_hc==2,1],s=100,c='green',label='Length3')

